FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY backend-disc/backend-disc.sln ./
COPY backend-disc/backend-disc/backend-disc.csproj backend-disc/
COPY backend-disc/class-library-disc/class-library-disc.csproj class-library-disc/

RUN dotnet restore backend-disc/backend-disc.csproj

COPY backend-disc/backend-disc/ backend-disc/
COPY backend-disc/class-library-disc/ class-library-disc/

EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "watch", "run", "--project", "backend-disc/backend-disc.csproj", "--", "--urls", "http://+:5000"]
