namespace backend_disc.Dtos.Employees
{
    public class CreateNewEmployee
    {
        public required string PrivateEmail { get; set; }

        public required string PrivatePhone { get; set; }

        public required string FirstName { get; set; }

        public required string LastName { get; set; }

        public required int DepartmentId { get; set; }

        public int? PositionId { get; set; }

        public int? DiscProfileId { get; set; }

        public required string CPR { get; set; }

        //all of the following shall be empty because they will be autogenerated in service
        public string? WorkEmail { get; set; }
        public string? WorkPhone { get; set; }
        public string? ImagePath { get; set; }
        public string? Username { get; set; }
        public string? PasswordHash { get; set; }
        public int? UserRoleId { get; set; }


    }
}
