using System.ComponentModel.DataAnnotations;

namespace backend_disc.Dtos.Employees
{
    public class CreateNewEmployee
    {
        [Required(ErrorMessage = "Private email is required")]
        [EmailAddress(ErrorMessage = "Invalid email format")]
        [StringLength(255, MinimumLength = 5, ErrorMessage = "Private email must be between 1 and 255 characters")]
        public required string PrivateEmail { get; set; }

        [Required(ErrorMessage = "Private phone is required")]
        [StringLength(255, MinimumLength = 6, ErrorMessage = "Private phone must be between 1 and 255 characters")]
        [RegularExpression(@"^[\d+]+$", ErrorMessage = "Private phone can only contain numeric characters and +")]
        public required string PrivatePhone { get; set; }

        [Required(ErrorMessage = "First name is required")]
        [StringLength(255, MinimumLength = 1, ErrorMessage = "First name must be between 1 and 255 characters")]
        [RegularExpression(@"^[a-zA-ZæøåÆØÅ \-]+$", ErrorMessage = "First name can only contain alphabetic characters, spaces, and hyphens")]
        public required string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        [StringLength(255, MinimumLength = 1, ErrorMessage = "Last name must be between 1 and 255 characters")]
        [RegularExpression(@"^[a-zA-ZæøåÆØÅ \-]+$", ErrorMessage = "Last name can only contain alphabetic characters, spaces, and hyphens")]
        public required string LastName { get; set; }

        [Required(ErrorMessage = "Department ID is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Department ID must be greater than 0")]
        public required int DepartmentId { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Position ID must be greater than 0")]
        public int? PositionId { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Disc Profile ID must be greater than 0")]
        public int? DiscProfileId { get; set; }

        [Required(ErrorMessage = "CPR is required")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "CPR must be exactly 10 characters")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "CPR must contain only numeric characters")]
        public required string CPR { get; set; }

        //all of the following shall be null because they will be autogenerated in service
        public string? WorkEmail { get; set; }
        public string? WorkPhone { get; set; }
        public string? ImagePath { get; set; }
        public string? Username { get; set; }
        public string? PasswordHash { get; set; }
        public int? UserRoleId { get; set; }
    }
}
